package com.nivroos.tool;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nivroos.core.model.JsonSchema;
import com.nivroos.core.model.NivroTool;
import com.nivroos.core.model.ToolResult;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.springframework.ai.tool.ToolCallback;
import org.springframework.ai.tool.execution.ToolExecutionException;

/**
 * {@code @Tool} 注解路径的 {@link NivroTool} 适配器（包内可见；与 {@code McpToolAdapter} 对称）。
 *
 * <p>Name, description and schema come from {@code ToolCallback.getToolDefinition()} (generated by
 * Spring AI from the annotation); execution delegates to {@code call(json)}. This is schema
 * generation plus a call bridge only - Spring AI never runs the tool loop itself（宪法原则二）。
 *
 * <p>ToolExecutionException 被解包后重抛原异常：ToolExecutor 用 {@code e.getMessage()} 落审计并
 * 回填模型上下文，沙箱拒绝文案是契约可见的（FR-006），不能被包装异常的描述顶掉。
 */
class AnnotatedToolAdapter implements NivroTool {

  /** 与 core 侧一致：一次 JSON 编解码还原 ToolResult（research §2 的裁决）。 */
  private static final ObjectMapper MAPPER = new ObjectMapper();

  private final ToolCallback callback;

  AnnotatedToolAdapter(ToolCallback callback) {
    this.callback = callback;
  }

  @Override
  public String getName() {
    return callback.getToolDefinition().name();
  }

  @Override
  public String getDescription() {
    return callback.getToolDefinition().description();
  }

  @Override
  public JsonSchema getInputSchema() {
    return new JsonSchema(callback.getToolDefinition().inputSchema());
  }

  @SuppressFBWarnings(
      value = "THROWS_METHOD_THROWS_RUNTIMEEXCEPTION",
      justification = "有意为之：解包 Spring AI 的包装异常后原样重抛，让沙箱拒绝文案逐字到达审计与模型（契约可见的失败语义）")
  @Override
  public ToolResult execute(JsonNode input) {
    try {
      return MAPPER.readValue(callback.call(input.toString()), ToolResult.class);
    } catch (ToolExecutionException e) {
      throw unwrap(e);
    } catch (JsonProcessingException e) {
      throw new IllegalStateException("tool result is not a ToolResult JSON: " + getName(), e);
    }
  }

  /** 解包 Spring AI 的包装异常，保住原异常类型与文案（沙箱拒绝文案必须逐字到达审计与模型）。 */
  private static RuntimeException unwrap(ToolExecutionException e) {
    Throwable cause = e.getCause();
    if (cause == null) {
      return e;
    }
    return cause instanceof RuntimeException runtimeException
        ? runtimeException
        : new RuntimeException(cause.getMessage(), cause);
  }
}
