package com.nivroos.memory;

import com.nivroos.core.memory.MemoryScope;
import com.nivroos.core.memory.MemoryService;
import com.nivroos.core.model.ToolResult;
import java.util.List;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;

/**
 * 长期记忆内置工具（技术方案 §6.2，契约 contracts/memory-tools.md）。
 *
 * <p>US-4 switches the registration mechanism: the two tools are now {@code @Tool}-annotated
 * methods (schema generated by Spring AI) instead of hand-written {@code NivroTool} objects.
 * 工具名与参数名 逐字不变（AGENT.md 与契约按名引用），失败语义也不变：业务性失败**返回**失败结果，存储性失败 **抛异常**由既有 ToolExecutor 落审计。Audit,
 * retry and failure recording stay in the existing ToolExecutor path, so this module adds no audit
 * path of its own.
 */
public class MemoryTools {

  private final MemoryService memoryService;

  public MemoryTools(MemoryService memoryService) {
    this.memoryService = memoryService;
  }

  /**
   * 写入长期记忆。
   *
   * <p>scope 保持 String 而非枚举：注解 schema 无法表达 enum，若改用枚举，非法取值会在 Spring AI
   * 绑定阶段抛异常，语义就从「业务性失败」变成「异常性失败」（契约规定前者）。
   */
  @Tool(name = "save_memory", description = "写入长期记忆（核心区每轮全量注入且永不截断；归档区可被关键词检索）。")
  public ToolResult saveMemory(
      @ToolParam(description = "要记住的内容") String content,
      @ToolParam(
              required = false,
              description = "写入分区：CORE 核心区（长期有效、每轮注入、永不截断），ARCHIVAL 归档区（可检索、超限截断）。省略时按 ARCHIVAL")
          String scope) {
    if (content == null || content.isBlank()) {
      // 契约：content 缺失/空 → 失败结果，由 ToolExecutor 落失败审计
      return new ToolResult(false, null, "save_memory 需要非空的 content 参数", false);
    }

    MemoryScope targetScope;
    if (scope == null || scope.isBlank()) {
      // 省略 → 让 MemoryService 按契约默认 ARCHIVAL（默认值只此一处定义，避免两处漂移）
      targetScope = null;
    } else if ("CORE".equals(scope)) {
      targetScope = MemoryScope.CORE;
    } else if ("ARCHIVAL".equals(scope)) {
      targetScope = MemoryScope.ARCHIVAL;
    } else {
      // 契约：非法取值不静默按默认处理
      return new ToolResult(false, null, "非法 scope: " + scope + "（合法取值：CORE、ARCHIVAL）", false);
    }

    memoryService.save(content, targetScope); // 存储失败上抛，由 ToolExecutor 落失败审计（FR-012）
    return new ToolResult(
        true, targetScope == MemoryScope.CORE ? "已写入核心记忆区" : "已写入归档记忆区", null, false);
  }

  /** 按关键词检索归档记忆（核心区每轮已全量注入，不参与检索）。 */
  @Tool(name = "recall_memory", description = "按关键词检索归档记忆（核心区每轮已全量注入，不参与检索）。")
  public ToolResult recallMemory(@ToolParam(description = "检索关键词") String query) {
    if (query == null || query.isBlank()) {
      return new ToolResult(false, null, "recall_memory 需要非空的 query 参数", false);
    }
    List<String> hits = memoryService.recall(query); // 存储失败上抛，由 ToolExecutor 落失败审计
    if (hits.isEmpty()) {
      // 「无匹配」文案归工具层：store 只回答有没有，措辞不能散落三个后端（也不回显关键词，
      // 否则模型会把回显当成命中内容）
      return new ToolResult(true, "无匹配：归档记忆中没有包含该关键词的内容", null, false);
    }
    return new ToolResult(true, String.join("\n", hits), null, false);
  }
}
